export enum Endpoints {
  ME = '/users/me/',
  JWT_CREATE = '/jwt/create/',
  JWT_REFRESH = '/jwt/refresh/',
  JWT_VERIFY = '/jwt/verify/',
  SET_PASSWORD = '/users/set_password/',
  USERS = '/users/',
  USER_ROLES = 'user-roles/',
  USER_ACTIVATION = '/users/activation/',
  RESEND_ACTIVATION = '/users/resend_activation/',
  RESET_PASSWORD = '/users/reset_password/',
  RESET_CONFIRM_PASSWORD = '/users/reset_password_confirm/',
  PAYMENT_LINKS = '/payment-links/',
  KYC_DOCUMENTS_TYPES = '/kyc-documents-types/',
  KYC_DOCUMENTS = '/kyc-documents/',
  TRANSACTIONS = '/transactions/',
  WITHDRAWALS = '/withdrawals/',
  ACCOUNT_VERIFICATIONS = '/account-verifications',
  MERCHANTS = '/merchants/',
  SERVICES = '/services/',
  SERVICE_PICTURES = '/service-pictures/',
  REFUELING_PICTURES = '/refueling-pictures/',
  STORES = '/stores/',
  REPAIRS = '/repairs/',
  REPAIR_PICTURES = '/repair-pictures/',
  GARAGES = '/garages/',
  GROUPS = '/groups/',
  DRIVERS = '/drivers/',
  WEBSITE_INTEGRATIONS = '/website-integrations/',
  TOURINGS = '/tourings/',
  TOURING_ADDRESSES = '/touring-addresses/',
  RENTAL_COMPANIES = '/rental-companies/',
  VEHICLES = '/vehicles/',
  STORE_ASSIGNMENTS = '/store-assignments/',
  TOURING_ASSIGNMENTS = '/touring-assignments/',
  VEHICLE_PICTURES = '/vehicle-pictures/',
  VEHICLE_ASSIGNMENTS = '/vehicle-assignments/',
  VEHICLE_RENTALS = '/vehicle-rentals/',
  VEHICLE_RENTAL_START_PICTURES = '/vehicle-rental-start-pictures/',
  VEHICLE_RENTAL_END_PICTURES = '/vehicle-rental-end-pictures/',
  STATS = 'stats/global_stats/?period=daily',
  COMBINED_STATS = '/combined_stats/',
  AFRIBAPAY_PAYOUT = '/afribapay/payout/',
  AFRIBAPAY_WEBHOOK = '/afribapay/webhook/',

  // Nouveaux endpoints pour les fonctionnalités backend
  ACCOUNT_SUSPENSIONS = '/account-suspensions/',
  PAYMENT_LINK_STATS = '/merchants/{id}/stats/',
  MERCHANT_BALANCE = '/merchants/{id}/balance/',
  WITHDRAWAL_APPROVE = '/withdrawals/{id}/approve/',
  WITHDRAWAL_REJECT = '/withdrawals/{id}/reject/',
  KYC_APPROVE = '/kyc-documents/{id}/approve/',
  KYC_REJECT = '/kyc-documents/{id}/reject/',
  TRANSACTION_REFUND = '/transactions/{id}/refund/',
}
export const API_RESULTS_SIZE = 20;
