export enum Pages {
  REGISTER = '/auth/register',
  LOGIN = '/auth/login',
  NOT_FOUND = '/not-found',
  NON_AUTHORIZED = '/non-authorized',
  USERS = '/users',
  PAYMENT_LINKS = '/payment-links',
  TRANSACTIONS = '/transactions',
  WITHDRAWALS = '/withdrawals',
  OUR_PRICES = '/our-prices',
  OUR_SPECIALITY = 'our-speciality',
  ACCOUNT_VERIFICATIONS = '/account-verifications',
  MERCHANTS = '/merchants',
  KYC = '/kyc',
  SERVICES = '/services',
  VEHICLES = '/vehicles',
  PROFILE = '/me/profile',
  MY_MERCHANTS = '/me/merchants',
  ME = '/me',
  BOARD = '/board',
  PASSWORD_FORGOT = '/auth/password-forgot',
  PASSWORD_RESET = '/auth/password-reset',
  PRIVACY_POLICY = '/privacy-policy',
  INTEGRATIONS = '/integrations',
  API = '/api',
}

export enum Styles {
  PRIMARY = '#dc2626',
  SECONDARY = '#5c1a1b',
  PRIMARY_BLACK = '#000704',
  BACKGROUND_DARK_GREEN = '#22403E',
  TERTIARY_LIGHT_BLUE = '#e6f6ff',
  ADDITIONAL_GRAY = '#DBDBDB',
  TEXT_GRAY = '#6b7280',
}
